-- Run manually in Supabase SQL Editor before deploying the new FE and BE.
-- This migration preserves all six legacy devices.*_time columns and their data.
BEGIN;

CREATE TABLE IF NOT EXISTS public.device_schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id INTEGER NOT NULL REFERENCES public.devices(id) ON DELETE CASCADE,
  relay_name TEXT NOT NULL CHECK (relay_name IN ('Pump', 'Light', 'Aerator')),
  on_time TIME,
  off_time TIME,
  is_daily BOOLEAN NOT NULL DEFAULT FALSE,
  run_date DATE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  on_executed_on DATE,
  off_executed_on DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT device_schedules_has_time CHECK (on_time IS NOT NULL OR off_time IS NOT NULL),
  CONSTRAINT device_schedules_mode_date CHECK (
    (is_daily AND run_date IS NULL) OR (NOT is_daily AND run_date IS NOT NULL)
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS device_schedules_one_active_per_relay
  ON public.device_schedules(device_id, relay_name) WHERE is_active;
CREATE INDEX IF NOT EXISTS device_schedules_active_idx
  ON public.device_schedules(is_active, device_id);

-- Existing times become daily schedules. Invalid legacy HH:MM values are ignored,
-- so the original columns remain available for manual correction.
WITH legacy AS (
  SELECT d.id AS device_id, v.relay_name, v.on_text, v.off_text
  FROM public.devices d
  CROSS JOIN LATERAL (VALUES
    ('Pump', d.pump_on_time, d.pump_off_time),
    ('Light', d.light_on_time, d.light_off_time),
    ('Aerator', d.aerator_on_time, d.aerator_off_time)
  ) AS v(relay_name, on_text, off_text)
)
INSERT INTO public.device_schedules(device_id, relay_name, on_time, off_time, is_daily)
SELECT device_id, relay_name,
  CASE WHEN on_text ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' THEN on_text::time END,
  CASE WHEN off_text ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' THEN off_text::time END,
  TRUE
FROM legacy
WHERE (on_text ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'
    OR off_text ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$')
  AND NOT EXISTS (
    SELECT 1 FROM public.device_schedules s
    WHERE s.device_id = legacy.device_id
      AND s.relay_name = legacy.relay_name AND s.is_active
  );

ALTER TABLE public.device_schedules ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE ON public.device_schedules TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.device_schedules_id_seq TO authenticated;
GRANT ALL ON public.device_schedules TO service_role;
GRANT ALL ON SEQUENCE public.device_schedules_id_seq TO service_role;

DROP POLICY IF EXISTS device_schedules_owner_select ON public.device_schedules;
DROP POLICY IF EXISTS device_schedules_owner_insert ON public.device_schedules;
DROP POLICY IF EXISTS device_schedules_owner_update ON public.device_schedules;
CREATE POLICY device_schedules_owner_select ON public.device_schedules
  FOR SELECT TO authenticated USING (
    EXISTS (SELECT 1 FROM public.devices d JOIN public.tanks t ON t.id = d.tank_id
      WHERE d.id = device_id AND t.user_id = auth.uid())
  );
CREATE POLICY device_schedules_owner_insert ON public.device_schedules
  FOR INSERT TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM public.devices d JOIN public.tanks t ON t.id = d.tank_id
      WHERE d.id = device_id AND t.user_id = auth.uid())
  );
CREATE POLICY device_schedules_owner_update ON public.device_schedules
  FOR UPDATE TO authenticated USING (
    EXISTS (SELECT 1 FROM public.devices d JOIN public.tanks t ON t.id = d.tank_id
      WHERE d.id = device_id AND t.user_id = auth.uid())
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM public.devices d JOIN public.tanks t ON t.id = d.tank_id
      WHERE d.id = device_id AND t.user_id = auth.uid())
  );

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'device_schedules'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.device_schedules;
  END IF;
END $$;

COMMIT;

-- Optional read-only verification after running:
-- SELECT device_id, relay_name, on_time, off_time, is_daily, run_date, is_active
-- FROM public.device_schedules ORDER BY device_id, relay_name;
